Repository Team-SE-MO/semo-springboot-server, pull requests merged in 2024-11, with the labels that each got.

#37 [Feat] JWT 인증/인가 구현
  semo-api/build.gradle
  semo-api/src/main/java/sandbox/semo/application/common/config/CorsConfig.java
  semo-api/src/main/java/sandbox/semo/application/common/config/CorsMvcConfig.java
  semo-api/src/main/java/sandbox/semo/application/common/config/SecurityConfig.java
  semo-api/src/main/java/sandbox/semo/application/security/authentication/JwtAuthenticationFilter.java
  semo-api/src/main/java/sandbox/semo/application/security/authentication/JwtMemberDetails.java
  semo-api/src/main/java/sandbox/semo/application/security/authentication/LoginFilter.java
  semo-api/src/main/java/sandbox/semo/application/security/authentication/LoginMemberDetailService.java
  semo-api/src/main/java/sandbox/semo/application/security/authentication/LoginMemberDetails.java
  semo-api/src/main/java/sandbox/semo/application/security/authentication/MemberAuthFailureHandler.java
  semo-api/src/main/java/sandbox/semo/application/security/authentication/MemberAuthProvider.java
  semo-api/src/main/java/sandbox/semo/application/security/authentication/MemberAuthSuccessHandler.java
  semo-api/src/main/java/sandbox/semo/application/security/constant/SecurityConstants.java
  semo-api/src/main/java/sandbox/semo/application/security/exception/AuthErrorCode.java
  semo-api/src/main/java/sandbox/semo/application/security/util/JwtUtil.java
Labels: 👷🏻 Build, ✨ Feat

#36 [Feat] 전체 유저 목록조회(필터링,검색)
  semo-api/src/main/java/sandbox/semo/application/common/exception/CommonBusinessException.java
  semo-api/src/main/java/sandbox/semo/application/company/controller/CompanyController.java
  semo-api/src/main/java/sandbox/semo/application/company/service/CompanyService.java
  semo-api/src/main/java/sandbox/semo/application/company/service/CompanyServiceImpl.java
  semo-api/src/main/java/sandbox/semo/application/member/controller/MemberController.java
  semo-api/src/main/java/sandbox/semo/application/member/service/MemberService.java
  semo-api/src/main/java/sandbox/semo/application/member/service/MemberServiceImpl.java
  semo-core/src/main/java/sandbox/semo/domain/common/dto/response/FormDecisionResponse.java
  semo-core/src/main/java/sandbox/semo/domain/company/entity/CompanyForm.java
  semo-core/src/main/java/sandbox/semo/domain/member/dto/request/MemberSearchFilter.java
  semo-core/src/main/java/sandbox/semo/domain/member/dto/response/MemberInfo.java
  semo-core/src/main/java/sandbox/semo/domain/member/entity/MemberForm.java
  semo-core/src/main/java/sandbox/semo/domain/member/repository/MemberRepository.java
Labels: ✨ Feat, ♻️ Refactor

#39 [Feat] 회사별 디바이스 요약 정보 페이지에서 필요한 디바이스 요약 데이터 조회 API 구현
  semo-api/src/main/java/sandbox/semo/application/common/exception/CommonBusinessException.java
  semo-api/src/main/java/sandbox/semo/application/company/exception/CompanyErrorCode.java
  semo-api/src/main/java/sandbox/semo/application/device/controller/DeviceController.java
  semo-api/src/main/java/sandbox/semo/application/device/service/DeviceService.java
  semo-api/src/main/java/sandbox/semo/application/device/service/DeviceServiceImpl.java
  semo-api/src/main/java/sandbox/semo/application/email/controller/EmailController.java
  semo-api/src/main/java/sandbox/semo/application/email/service/EmailService.java
  semo-api/src/main/java/sandbox/semo/application/email/service/EmailServiceImpl.java
  semo-api/src/main/java/sandbox/semo/application/member/controller/MemberController.java
  semo-api/src/main/java/sandbox/semo/application/monitoring/controller/MonitoringController.java
  semo-api/src/main/java/sandbox/semo/application/monitoring/service/MonitoringService.java
  semo-api/src/main/java/sandbox/semo/application/monitoring/service/MonitoringServiceImpl.java
  semo-batch/src/main/java/sandbox/semo/batch/config/BatchConfig.java
  semo-batch/src/main/java/sandbox/semo/batch/repository/JdbcRepository.java
  semo-batch/src/main/java/sandbox/semo/batch/service/step/DeviceProcessor.java
  semo-batch/src/main/java/sandbox/semo/batch/service/step/DeviceWriter.java
  semo-core/src/main/java/sandbox/semo/domain/common/config/QueryLoader.java
  semo-core/src/main/java/sandbox/semo/domain/common/util/HikariDataSourceUtil.java
  semo-core/src/main/java/sandbox/semo/domain/common/util/ParameterSourceConverter.java
  semo-core/src/main/java/sandbox/semo/domain/device/repository/DeviceRepository.java
  semo-core/src/main/java/sandbox/semo/domain/member/repository/MemberRepository.java
  semo-core/src/main/java/sandbox/semo/domain/monitoring/dto/request/DeviceCollectionInfo.java
  semo-core/src/main/java/sandbox/semo/domain/monitoring/dto/response/DeviceConnectInfo.java
  semo-core/src/main/java/sandbox/semo/domain/monitoring/dto/response/MetricSummary.java
  semo-core/src/main/java/sandbox/semo/domain/monitoring/dto/response/SummaryPageData.java
  semo-core/src/main/java/sandbox/semo/domain/monitoring/dto/response/TotalProcessInfo.java
  semo-core/src/main/java/sandbox/semo/domain/monitoring/entity/MonitoringMetric.java
  semo-core/src/main/java/sandbox/semo/domain/monitoring/entity/MonitoringMetricId.java
  semo-core/src/main/java/sandbox/semo/domain/monitoring/entity/SessionData.java
  semo-core/src/main/java/sandbox/semo/domain/monitoring/entity/SessionDataId.java
  semo-core/src/main/java/sandbox/semo/domain/monitoring/repository/MonitoringRepository.java
  semo-core/src/main/java/sandbox/semo/domain/monitoring/repository/mapper/MetricDataRowMapper.java
  semo-core/src/main/java/sandbox/semo/domain/monitoring/repository/mapper/SessionDataRowMapper.java
  semo-core/src/main/resources/sql/batch-queries.properties
Labels: ✨ Feat, ♻️ Refactor

#43 [Feat] 멀티스레드 구현하여 배치 성능 최적화 진행
  semo-batch/src/main/java/sandbox/semo/batch/config/BatchConfig.java
  semo-batch/src/main/java/sandbox/semo/batch/service/step/DeviceProcessor.java
  semo-batch/src/main/java/sandbox/semo/batch/service/step/DeviceReader.java
  semo-batch/src/main/java/sandbox/semo/batch/service/step/DeviceReaderListener.java
  semo-batch/src/main/java/sandbox/semo/batch/service/step/DeviceWriter.java
  semo-core/src/main/java/sandbox/semo/domain/common/util/HikariDataSourceUtil.java
  semo-core/src/main/java/sandbox/semo/domain/common/util/ParameterSourceConverter.java
  semo-core/src/main/java/sandbox/semo/domain/monitoring/repository/MonitoringRepository.java
  semo-core/src/main/resources/sql/batch-queries.properties
Labels: ✨ Feat, ♻️ Refactor

#46 [Feat] Redis 적용하여 로그아웃 시 토큰 블랙리스트 관리 기능 구현
  semo-api/build.gradle
  semo-api/src/main/java/sandbox/semo/application/common/config/RedisConfig.java
  semo-api/src/main/java/sandbox/semo/application/common/config/SecurityConfig.java
  semo-api/src/main/java/sandbox/semo/application/security/authentication/JwtAuthenticationFilter.java
  semo-api/src/main/java/sandbox/semo/application/security/authentication/JwtLogoutHandler.java
  semo-api/src/main/java/sandbox/semo/application/security/authentication/JwtLogoutSuccessHandler.java
  semo-api/src/main/java/sandbox/semo/application/security/authentication/LoginFilter.java
  semo-api/src/main/java/sandbox/semo/application/security/exception/AuthErrorCode.java
  semo-api/src/main/java/sandbox/semo/application/security/exception/MemberAuthExceptionEntryPoint.java
  semo-api/src/main/java/sandbox/semo/application/security/util/RedisUtil.java
  semo-api/src/main/java/sandbox/semo/application/security/util/TokenExtractor.java
  semo-api/src/main/resources/application.yml
Labels: 🍎 Chore, ✨ Feat

#48 [Refactor] Member 비밀번호 변경 flag 추가, JWT payload 추가 및 필터처리
  semo-api/src/main/java/sandbox/semo/application/common/config/SecurityConfig.java
  semo-api/src/main/java/sandbox/semo/application/security/authentication/JwtAuthenticationFilter.java
  semo-api/src/main/java/sandbox/semo/application/security/authentication/LoginFilter.java
  semo-api/src/main/java/sandbox/semo/application/security/authentication/LoginMemberDetails.java
  semo-api/src/main/java/sandbox/semo/application/security/constant/SecurityConstants.java
  semo-api/src/main/java/sandbox/semo/application/security/util/JwtUtil.java
  semo-core/src/main/java/sandbox/semo/domain/member/entity/Member.java
Labels: ♻️ Refactor

#53 [Refactor] 인증 코드 발송 API 분리
  semo-api/src/main/java/sandbox/semo/application/email/controller/EmailController.java
  semo-api/src/main/java/sandbox/semo/application/email/service/EmailService.java
  semo-api/src/main/java/sandbox/semo/application/email/service/EmailServiceImpl.java
Labels: ♻️ Refactor

#56 [Fix] 이메일 인증 세션 로직 제거, Redis 적용 및 코드 리팩토링
  semo-api/src/main/java/sandbox/semo/application/SemoServiceApplication.java
  semo-api/src/main/java/sandbox/semo/application/common/config/EmailConfig.java
  semo-api/src/main/java/sandbox/semo/application/email/constants/EmailConstants.java
  semo-api/src/main/java/sandbox/semo/application/email/controller/EmailController.java
  semo-api/src/main/java/sandbox/semo/application/email/exception/EmailErrorCode.java
  semo-api/src/main/java/sandbox/semo/application/email/service/EmailService.java
  semo-api/src/main/java/sandbox/semo/application/email/service/EmailServiceImpl.java
  semo-api/src/main/java/sandbox/semo/application/email/service/EmergencyCache.java
  semo-api/src/main/java/sandbox/semo/application/member/controller/MemberController.java
  semo-api/src/main/java/sandbox/semo/application/member/service/MemberService.java
  semo-api/src/main/java/sandbox/semo/application/member/service/MemberServiceImpl.java
  semo-api/src/main/java/sandbox/semo/application/security/constant/SecurityConstants.java
  semo-api/src/main/resources/application.yml
  semo-api/src/main/resources/img/logo.png
  semo-core/src/main/java/sandbox/semo/domain/member/dto/request/EmailAuthVerify.java
  semo-core/src/main/java/sandbox/semo/domain/member/dto/request/UpdatePassword.java
  semo-core/src/main/java/sandbox/semo/domain/member/repository/MemberRepository.java
Labels: 🐞 Bug, ✨ Feat, ♻️ Refactor, :hammer: Fix

#54 [Feat] Session Data Monitoring Chart Data 실시간 처리 기능 구현
  semo-api/build.gradle
  semo-api/src/main/java/sandbox/semo/application/common/config/WebSocketConfig.java
  semo-api/src/main/java/sandbox/semo/application/common/controller/CommonController.java
  semo-api/src/main/java/sandbox/semo/application/common/service/CommonService.java
  semo-api/src/main/java/sandbox/semo/application/common/service/CommonServiceImpl.java
  semo-api/src/main/java/sandbox/semo/application/email/service/EmailServiceImpl.java
  semo-api/src/main/java/sandbox/semo/application/monitoring/controller/MonitoringController.java
  semo-api/src/main/java/sandbox/semo/application/monitoring/socket/MonitoringWebSocketHandler.java
  semo-api/src/main/java/sandbox/semo/application/monitoring/socket/WebSocketHandShakeInterceptor.java
  semo-api/src/main/java/sandbox/semo/application/monitoring/socket/WebSocketService.java
  semo-api/src/main/java/sandbox/semo/application/security/authentication/JwtAuthenticationFilter.java
  semo-api/src/main/java/sandbox/semo/application/security/authentication/JwtLogoutHandler.java
  semo-api/src/main/java/sandbox/semo/application/security/constant/SecurityConstants.java
  semo-api/src/main/java/sandbox/semo/application/security/util/TokenExtractor.java
  semo-api/src/main/resources/templates/company-registration.html
  semo-api/src/main/resources/templates/company-rejection.html
  semo-api/src/main/resources/templates/member-registration.html
  semo-api/src/main/resources/templates/member-rejection.html
  semo-api/src/main/resources/templates/send-auth-code.html
  semo-core/src/main/java/sandbox/semo/domain/monitoring/dto/request/DeviceMonitoring.java
Labels: ✨ Feat, 🧐 Tech

#59 [ Fix] Email 검증 권한 추가 및 Email 중복 체크
  semo-api/src/main/java/sandbox/semo/application/email/controller/EmailController.java
  semo-api/src/main/java/sandbox/semo/application/member/exception/MemberErrorCode.java
  semo-api/src/main/java/sandbox/semo/application/member/service/MemberServiceImpl.java
  semo-api/src/main/resources/templates/member-registration.html
  semo-core/src/main/java/sandbox/semo/domain/member/repository/MemberRepository.java
Labels: :hammer: Fix

#62 [Feat] Device 수정, 삭제 API 구현
  semo-api/src/main/java/sandbox/semo/application/device/controller/DeviceController.java
  semo-api/src/main/java/sandbox/semo/application/device/exception/DeviceErrorCode.java
  semo-api/src/main/java/sandbox/semo/application/device/service/DeviceService.java
  semo-api/src/main/java/sandbox/semo/application/device/service/DeviceServiceImpl.java
  semo-core/src/main/java/sandbox/semo/domain/device/dto/request/DeviceUpdate.java
  semo-core/src/main/java/sandbox/semo/domain/device/entity/Device.java
  semo-core/src/main/java/sandbox/semo/domain/device/repository/DeviceRepository.java
Labels: ✨ Feat

#63 [Fix] 사용자 요청 폼(MemberForm) 조회 수정
  semo-api/src/main/java/sandbox/semo/application/company/controller/CompanyController.java
  semo-api/src/main/java/sandbox/semo/application/company/service/CompanyService.java
  semo-api/src/main/java/sandbox/semo/application/company/service/CompanyServiceImpl.java
  semo-api/src/main/java/sandbox/semo/application/member/controller/MemberController.java
  semo-api/src/main/java/sandbox/semo/application/member/service/MemberService.java
  semo-api/src/main/java/sandbox/semo/application/member/service/MemberServiceImpl.java
  semo-core/src/main/java/sandbox/semo/domain/common/dto/response/OffsetPage.java
  semo-core/src/main/java/sandbox/semo/domain/company/repository/CompanyFormRepository.java
  semo-core/src/main/java/sandbox/semo/domain/member/repository/MemberFormRepository.java
Labels: :hammer: Fix

#60 [Feat] 배치 CSV 적재, 삭제 Job 추가 및 스케쥴러 등록
  build.gradle
  semo-api/build.gradle
  semo-api/src/main/java/sandbox/semo/application/file/controller/FileController.java
  semo-api/src/main/java/sandbox/semo/application/file/exception/FileBusinessException.java
  semo-api/src/main/java/sandbox/semo/application/file/exception/FileErrorCode.java
  semo-api/src/main/java/sandbox/semo/application/file/service/FileService.java
  semo-api/src/main/java/sandbox/semo/application/file/service/FileServiceImpl.java
  semo-batch/src/main/java/sandbox/semo/batch/config/BatchConfig.java
  semo-batch/src/main/java/sandbox/semo/batch/scheduler/RetentionScheduler.java
  semo-batch/src/main/java/sandbox/semo/batch/scheduler/SessionDataScheduler.java
  semo-batch/src/main/java/sandbox/semo/batch/scheduler/StoreCsvFileScheduler.java
  semo-batch/src/main/java/sandbox/semo/batch/service/step/CompanyPartitionedFileWriter.java
  semo-batch/src/main/java/sandbox/semo/batch/service/step/DailyTimeRangePartitioner.java
  semo-batch/src/main/java/sandbox/semo/batch/service/tasklet/DeleteMetaDataTasklet.java
  semo-batch/src/main/java/sandbox/semo/batch/service/tasklet/DeleteTasklet.java
  semo-batch/src/main/java/sandbox/semo/batch/service/tasklet/S3UploadTasklet.java
  semo-batch/src/main/resources/application.yml
  semo-core/src/main/java/sandbox/semo/domain/common/config/S3Config.java
  semo-core/src/main/java/sandbox/semo/domain/file/dto/CsvFileInfo.java
  semo-core/src/main/java/sandbox/semo/domain/monitoring/dto/request/CsvFileData.java
  semo-core/src/main/java/sandbox/semo/domain/monitoring/repository/MonitoringRepository.java
  semo-core/src/main/java/sandbox/semo/domain/monitoring/repository/mapper/CsvFileDataRowMapper.java
  semo-core/src/main/resources/sql/batch-queries.properties
Labels: ✨ Feat, ♻️ Refactor

#65 [Feat] 배치 모니터링 조회 API
  semo-api/src/main/java/sandbox/semo/application/monitoring/controller/MonitoringController.java
  semo-api/src/main/java/sandbox/semo/application/monitoring/service/MonitoringService.java
  semo-api/src/main/java/sandbox/semo/application/monitoring/service/MonitoringServiceImpl.java
  semo-core/src/main/java/sandbox/semo/domain/monitoring/dto/response/DailyJobData.java
  semo-core/src/main/java/sandbox/semo/domain/monitoring/dto/response/DailyJobExecutionInfo.java
  semo-core/src/main/java/sandbox/semo/domain/monitoring/dto/response/MetaExecutionData.java
  semo-core/src/main/java/sandbox/semo/domain/monitoring/dto/response/StepData.java
  semo-core/src/main/java/sandbox/semo/domain/monitoring/dto/response/StepInfo.java
  semo-core/src/main/java/sandbox/semo/domain/monitoring/repository/MonitoringRepository.java
  semo-core/src/main/resources/sql/batch-queries.properties
Labels: ✨ Feat, :hammer: Fix

#67 [Feat] 장비(Device)별 SessionData 정보 조회 API - CollectedAt 기준으로 조회
  semo-api/src/main/java/sandbox/semo/application/monitoring/controller/MonitoringController.java
  semo-api/src/main/java/sandbox/semo/application/monitoring/service/MonitoringService.java
  semo-api/src/main/java/sandbox/semo/application/monitoring/service/MonitoringServiceImpl.java
  semo-core/src/main/java/sandbox/semo/domain/common/dto/response/CursorPage.java
  semo-core/src/main/java/sandbox/semo/domain/monitoring/dto/response/SessionDataInfo.java
  semo-core/src/main/java/sandbox/semo/domain/monitoring/repository/SessionDataRepository.java
Labels: ✨ Feat

#69 [Refactor] 멀티모듈 추가 및 리팩토링 진행
  semo-api/src/main/java/sandbox/semo/application/file/service/FileServiceImpl.java
  semo-batch-collect/.gitignore
  semo-batch-collect/build.gradle
  semo-batch-collect/src/main/java/sandbox/semo/batch/SemoBatchCollectApplication.java
  semo-batch-collect/src/main/java/sandbox/semo/batch/config/BatchConfig.java
  semo-batch-collect/src/main/java/sandbox/semo/batch/scheduler/SessionDataScheduler.java
  semo-batch-collect/src/main/java/sandbox/semo/batch/service/step/DeviceProcessor.java
  semo-batch-collect/src/main/java/sandbox/semo/batch/service/step/DeviceReaderListener.java
  semo-batch-collect/src/main/java/sandbox/semo/batch/service/step/DeviceWriter.java
  semo-batch-collect/src/main/resources/application.yml
  semo-batch-collect/src/main/resources/banner.txt
  semo-batch-retention/.gitignore
  semo-batch-retention/build.gradle
  semo-batch-retention/src/main/java/sandbox/semo/batch/SemoBatchRetentionApplication.java
  semo-batch-retention/src/main/java/sandbox/semo/batch/config/BatchConfig.java
  semo-batch-retention/src/main/java/sandbox/semo/batch/scheduler/RetentionScheduler.java
  semo-batch-retention/src/main/java/sandbox/semo/batch/scheduler/StoreCsvFileScheduler.java
  semo-batch-retention/src/main/java/sandbox/semo/batch/service/step/CompanyPartitionedFileWriter.java
  semo-batch-retention/src/main/java/sandbox/semo/batch/service/step/DailyTimeRangePartitioner.java
  semo-batch-retention/src/main/java/sandbox/semo/batch/service/tasklet/DeleteMetaDataTasklet.java
  semo-batch-retention/src/main/java/sandbox/semo/batch/service/tasklet/DeleteTasklet.java
  semo-batch-retention/src/main/java/sandbox/semo/batch/service/tasklet/S3UploadTasklet.java
  semo-batch-retention/src/main/resources/application.yml
  semo-batch-retention/src/main/resources/banner.txt
  settings.gradle
Labels: 👷🏻 Build, 🍎 Chore, ♻️ Refactor

#74 [Bug] 배치 모니터링 최신 데이터 응답 값 쿼리 수정 및 장비 요약 페이지 조회 정렬 기준 수정
  semo-api/src/main/java/sandbox/semo/application/monitoring/service/MonitoringServiceImpl.java
  semo-core/src/main/java/sandbox/semo/domain/device/repository/DeviceRepository.java
  semo-core/src/main/resources/sql/batch-queries.properties
Labels: 🐞 Bug, :hammer: Fix

#76 [Deploy] 배포 설정
  .github/workflows/gradle.yml
  semo-api/Dockerfile
  semo-batch-collect/Dockerfile
  semo-batch-retention/Dockerfile
  semo-batch-retention/src/main/resources/application.yml
Labels: 🌎 Deploy
