Repository Team-SE-MO/semo-springboot-server, pull requests merged in 2024-10, with the labels that each got.

#2 [Feat] Spring Security 설정 및 로그인, 로그아웃 구현
  src/main/java/sandbox/semo/common/config/SecurityConfig.java
  src/main/java/sandbox/semo/common/entity/BaseTime.java
  src/main/java/sandbox/semo/company/entity/Company.java
  src/main/java/sandbox/semo/company/repository/CompanyRepository.java
  src/main/java/sandbox/semo/member/controller/MemberController.java
  src/main/java/sandbox/semo/member/dto/request/MemberRegister.java
  src/main/java/sandbox/semo/member/entity/Member.java
  src/main/java/sandbox/semo/member/entity/Role.java
  src/main/java/sandbox/semo/member/repository/MemberRepository.java
  src/main/java/sandbox/semo/member/service/MemberService.java
  src/main/java/sandbox/semo/member/service/MemberServiceImpl.java
  src/main/java/sandbox/semo/security/authentication/MemberAuthFailureHandler.java
  src/main/java/sandbox/semo/security/authentication/MemberAuthProvider.java
  src/main/java/sandbox/semo/security/authentication/MemberAuthSuccessHandler.java
  src/main/java/sandbox/semo/security/authentication/MemberPrincipalDetailService.java
  src/main/java/sandbox/semo/security/authentication/MemberPrincipalDetails.java
  src/main/java/sandbox/semo/security/exception/ErrorCode.java
  src/main/java/sandbox/semo/security/exception/MemberAuthExceptionEntryPoint.java
  src/main/java/sandbox/semo/security/util/JsonResponseHelper.java
Labels: 👷🏻 Build, ✨ Feat

#4 [Feat] 공통 응답 환경 구성 (API 응답, 예외 처리 응답)
  src/main/java/sandbox/semo/common/exception/CommonErrorCode.java
  src/main/java/sandbox/semo/common/exception/ErrorCode.java
  src/main/java/sandbox/semo/common/exception/GlobalExceptionHandler.java
  src/main/java/sandbox/semo/common/response/ApiResponse.java
  src/main/java/sandbox/semo/member/exception/MemberBusinessException.java
  src/main/java/sandbox/semo/member/exception/MemberErrorCode.java
  src/main/java/sandbox/semo/security/authentication/MemberAuthFailureHandler.java
  src/main/java/sandbox/semo/security/authentication/MemberAuthProvider.java
  src/main/java/sandbox/semo/security/authentication/MemberAuthSuccessHandler.java
  src/main/java/sandbox/semo/security/authentication/MemberPrincipalDetailService.java
  src/main/java/sandbox/semo/security/exception/AuthErrorCode.java
  src/main/java/sandbox/semo/security/exception/ErrorCode.java
  src/main/java/sandbox/semo/security/exception/MemberAuthExceptionEntryPoint.java
  src/main/java/sandbox/semo/security/util/JsonResponseHelper.java
Labels: 👷🏻 Build

#9 [Feat] 회사 폼 요청 및 폼 요청 도메인 구현
  src/main/java/sandbox/semo/company/entity/Company.java
  src/main/java/sandbox/semo/company/repository/CompanyRepository.java
  src/main/java/sandbox/semo/form/dto/CompanyFormRegister.java
  src/main/java/sandbox/semo/form/entity/BaseForm.java
  src/main/java/sandbox/semo/form/entity/CompanyForm.java
  src/main/java/sandbox/semo/form/entity/MemberForm.java
  src/main/java/sandbox/semo/form/entity/Status.java
  src/main/java/sandbox/semo/form/exception/CompanyFormBusinessException.java
  src/main/java/sandbox/semo/form/exception/CompanyFormErrorCode.java
  src/main/java/sandbox/semo/form/repository/CompanyFormRepository.java
  src/main/java/sandbox/semo/form/repository/MemberFormRepository.java
  src/main/java/sandbox/semo/form/service/CompanyFormImpl.java
  src/main/java/sandbox/semo/form/service/CompanyFormService.java
  src/main/java/sandbox/semo/member/entity/Member.java
Labels: 🕋 DB, ✨ Feat, :hammer: Fix

#12 [Feat] 장비(DataBase) 등록 및 데이터베이스 상태 체크 API 구현
  semo-api/src/main/java/sandbox/semo/application/common/config/SecurityConfig.java
  semo-api/src/main/java/sandbox/semo/application/common/exception/CommonErrorCode.java
  semo-api/src/main/java/sandbox/semo/application/common/exception/ErrorCode.java
  semo-api/src/main/java/sandbox/semo/application/common/util/AES256.java
  semo-api/src/main/java/sandbox/semo/application/common/util/ApplicationContextUtil.java
  semo-api/src/main/java/sandbox/semo/application/device/controller/DeviceController.java
  semo-api/src/main/java/sandbox/semo/application/device/exception/DeviceBusinessException.java
  semo-api/src/main/java/sandbox/semo/application/device/exception/DeviceErrorCode.java
  semo-api/src/main/java/sandbox/semo/application/device/service/DeviceService.java
  semo-api/src/main/java/sandbox/semo/application/device/service/DeviceServiceImpl.java
  semo-api/src/main/java/sandbox/semo/application/member/exception/MemberBusinessException.java
  semo-api/src/main/java/sandbox/semo/application/member/exception/MemberErrorCode.java
  semo-api/src/main/java/sandbox/semo/application/security/exception/AuthErrorCode.java
  semo-core/src/main/java/sandbox/semo/domain/device/dto/request/DataBaseInfo.java
  semo-core/src/main/java/sandbox/semo/domain/device/dto/request/DeviceRegister.java
  semo-core/src/main/java/sandbox/semo/domain/device/entity/DatabaseType.java
  semo-core/src/main/java/sandbox/semo/domain/device/entity/Device.java
  semo-core/src/main/java/sandbox/semo/domain/device/repository/DeviceRepository.java
Labels: ✨ Feat

#15 [Feat] 장비(Device) 사용자 권한에 따른 데이터 조회 분기 처리
  semo-api/src/main/java/sandbox/semo/application/device/controller/DeviceController.java
  semo-api/src/main/java/sandbox/semo/application/device/service/DeviceService.java
  semo-api/src/main/java/sandbox/semo/application/device/service/DeviceServiceImpl.java
  semo-core/src/main/java/sandbox/semo/domain/device/dto/response/DeviceInfo.java
  semo-core/src/main/java/sandbox/semo/domain/device/repository/DeviceRepository.java
Labels: ✨ Feat

#18 [Feat] 회사 등록 및 회사 목록 조회 API 구현
  semo-api/src/main/java/sandbox/semo/application/company/controller/CompanyController.java
  semo-api/src/main/java/sandbox/semo/application/company/exception/CompanyBusinessException.java
  semo-api/src/main/java/sandbox/semo/application/company/exception/CompanyErrorCode.java
  semo-api/src/main/java/sandbox/semo/application/company/service/CompanyService.java
  semo-api/src/main/java/sandbox/semo/application/company/service/CompanyServiceImpl.java
  semo-api/src/main/java/sandbox/semo/application/form/controller/CompanyFormController.java
  semo-core/src/main/java/sandbox/semo/domain/company/entity/Company.java
  semo-core/src/main/java/sandbox/semo/domain/company/repository/CompanyRepository.java
Labels: ✨ Feat

#22 [Refactor] Form 패키지를 Company와 Member 도메인 패키지로 구조 리팩토링 및 병합
  semo-api/src/main/java/sandbox/semo/application/company/controller/CompanyController.java
  semo-api/src/main/java/sandbox/semo/application/company/exception/CompanyErrorCode.java
  semo-api/src/main/java/sandbox/semo/application/company/service/CompanyService.java
  semo-api/src/main/java/sandbox/semo/application/company/service/CompanyServiceImpl.java
  semo-api/src/main/java/sandbox/semo/application/form/controller/CompanyFormController.java
  semo-api/src/main/java/sandbox/semo/application/form/controller/MemberFormController.java
  semo-api/src/main/java/sandbox/semo/application/form/exception/CompanyFormBusinessException.java
  semo-api/src/main/java/sandbox/semo/application/form/exception/CompanyFormErrorCode.java
  semo-api/src/main/java/sandbox/semo/application/form/exception/MemberFormBusinessException.java
  semo-api/src/main/java/sandbox/semo/application/form/exception/MemberFormErrorCode.java
  semo-api/src/main/java/sandbox/semo/application/form/service/CompanyFormService.java
  semo-api/src/main/java/sandbox/semo/application/form/service/CompanyFormServiceImpl.java
  semo-api/src/main/java/sandbox/semo/application/form/service/MemberFormService.java
  semo-api/src/main/java/sandbox/semo/application/form/service/MemberFormServiceImpl.java
  semo-api/src/main/java/sandbox/semo/application/member/controller/MemberController.java
  semo-api/src/main/java/sandbox/semo/application/member/exception/MemberErrorCode.java
  semo-api/src/main/java/sandbox/semo/application/member/service/MemberService.java
  semo-api/src/main/java/sandbox/semo/application/member/service/MemberServiceImpl.java
  semo-core/src/main/java/sandbox/semo/domain/common/entity/BaseForm.java
  semo-core/src/main/java/sandbox/semo/domain/common/entity/FormStatus.java
  semo-core/src/main/java/sandbox/semo/domain/company/dto/request/CompanyFormDecision.java
  semo-core/src/main/java/sandbox/semo/domain/company/dto/request/CompanyFormRegister.java
  semo-core/src/main/java/sandbox/semo/domain/company/dto/response/CompanyFormInfo.java
  semo-core/src/main/java/sandbox/semo/domain/company/entity/CompanyForm.java
  semo-core/src/main/java/sandbox/semo/domain/company/repository/CompanyFormRepository.java
  semo-core/src/main/java/sandbox/semo/domain/form/entity/Status.java
  semo-core/src/main/java/sandbox/semo/domain/member/dto/request/MemberFormDecision.java
  semo-core/src/main/java/sandbox/semo/domain/member/dto/request/MemberFormRegister.java
  semo-core/src/main/java/sandbox/semo/domain/member/dto/response/MemberFormInfo.java
  semo-core/src/main/java/sandbox/semo/domain/member/entity/Member.java
  semo-core/src/main/java/sandbox/semo/domain/member/entity/MemberForm.java
  semo-core/src/main/java/sandbox/semo/domain/member/repository/MemberFormRepository.java
Labels: 🍎 Chore, ♻️ Refactor, ⭐️ Style

#24 [Feat] 회원가입 및 이메일 중복확인 API 구현
  semo-api/src/main/java/sandbox/semo/application/member/controller/MemberController.java
  semo-api/src/main/java/sandbox/semo/application/member/exception/MemberErrorCode.java
  semo-api/src/main/java/sandbox/semo/application/member/service/MemberService.java
  semo-api/src/main/java/sandbox/semo/application/member/service/MemberServiceImpl.java
  semo-api/src/main/java/sandbox/semo/application/member/service/helper/LoginIdGenerator.java
  semo-core/src/main/java/sandbox/semo/domain/member/dto/request/MemberRegister.java
  semo-core/src/main/java/sandbox/semo/domain/member/repository/MemberRepository.java
Labels: ✨ Feat, ⭐️ Style, :hammer: Fix

#27 [Feat] 등록 장비의 데이터 수집을 위한 Batch 시스템 구축 (Device 상태 최신화)
  build.gradle
  semo-api/build.gradle
  semo-api/src/main/java/sandbox/semo/application/SemoServiceApplication.java
  semo-api/src/main/java/sandbox/semo/application/common/config/SecurityConfig.java
  semo-api/src/main/java/sandbox/semo/application/common/util/ApplicationContextUtil.java
  semo-api/src/main/java/sandbox/semo/application/device/service/DeviceServiceImpl.java
  semo-api/src/main/resources/banner.txt
  semo-batch/build.gradle
  semo-batch/src/main/java/sandbox/semo/batch/SemoBatchApplication.java
  semo-batch/src/main/java/sandbox/semo/batch/config/BatchConfig.java
  semo-batch/src/main/java/sandbox/semo/batch/config/QueryLoader.java
  semo-batch/src/main/java/sandbox/semo/batch/dto/DeviceStatus.java
  semo-batch/src/main/java/sandbox/semo/batch/repository/JdbcRepository.java
  semo-batch/src/main/java/sandbox/semo/batch/scheduler/SessionDataScheduler.java
  semo-batch/src/main/java/sandbox/semo/batch/service/step/DeviceStatusProcessor.java
  semo-batch/src/main/java/sandbox/semo/batch/service/step/DeviceStatusReader.java
  semo-batch/src/main/java/sandbox/semo/batch/service/step/DeviceStatusWriter.java
  semo-batch/src/main/java/sandbox/semo/batch/util/HikariDataSourceUtil.java
  semo-batch/src/main/resources/application.yml
  semo-batch/src/main/resources/banner.txt
  semo-batch/src/main/resources/sql/batch-queries.properties
  semo-core/build.gradle
  semo-core/src/main/java/sandbox/semo/domain/collection/entity/SessionData.java
  semo-core/src/main/java/sandbox/semo/domain/collection/entity/SessionDataId.java
  semo-core/src/main/java/sandbox/semo/domain/common/crypto/AES256.java
  semo-core/src/main/java/sandbox/semo/domain/common/crypto/CryptoConfig.java
Labels: 👷🏻 Build, 🏗️ Const, ✨ Feat, ♻️ Refactor

#28 [Refactor] MemberForm 도메인에 CompanyName 컬럼 ➡ Company 변경 및 관련 로직 수정
  semo-api/src/main/java/sandbox/semo/application/member/service/MemberServiceImpl.java
  semo-core/src/main/java/sandbox/semo/domain/common/entity/BaseForm.java
  semo-core/src/main/java/sandbox/semo/domain/company/entity/CompanyForm.java
  semo-core/src/main/java/sandbox/semo/domain/member/dto/response/MemberFormInfo.java
  semo-core/src/main/java/sandbox/semo/domain/member/entity/MemberForm.java
Labels: 🍎 Chore, 🕋 DB, ♻️ Refactor, :hammer: Fix

#29 [Feat] 등록 장비의 데이터 수집을 위한 Batch 시스템 구축 (v$session 정보 수집)
  semo-batch/src/main/java/sandbox/semo/batch/config/BatchConfig.java
  semo-batch/src/main/java/sandbox/semo/batch/dto/DeviceInfo.java
  semo-batch/src/main/java/sandbox/semo/batch/repository/JdbcRepository.java
  semo-batch/src/main/java/sandbox/semo/batch/repository/mapper/SessionDataRowMapper.java
  semo-batch/src/main/java/sandbox/semo/batch/scheduler/SessionDataScheduler.java
  semo-batch/src/main/java/sandbox/semo/batch/service/step/DeviceProcessor.java
  semo-batch/src/main/java/sandbox/semo/batch/service/step/DeviceReader.java
  semo-batch/src/main/java/sandbox/semo/batch/service/step/DeviceWriter.java
  semo-batch/src/main/resources/sql/batch-queries.properties
  semo-core/src/main/java/sandbox/semo/domain/collection/entity/SessionData.java
Labels: ✨ Feat

#31 [Feat] 비밀번호 재설정 및 회원삭제(Soft delete) API 구현
  semo-api/src/main/java/sandbox/semo/application/common/config/SecurityConfig.java
  semo-api/src/main/java/sandbox/semo/application/common/exception/CommonBusinessException.java
  semo-api/src/main/java/sandbox/semo/application/device/service/DeviceServiceImpl.java
  semo-api/src/main/java/sandbox/semo/application/member/controller/MemberController.java
  semo-api/src/main/java/sandbox/semo/application/member/service/MemberService.java
  semo-api/src/main/java/sandbox/semo/application/member/service/MemberServiceImpl.java
  semo-api/src/main/java/sandbox/semo/application/member/service/helper/LoginIdGenerator.java
  semo-core/src/main/java/sandbox/semo/domain/member/dto/request/MemberRemove.java
  semo-core/src/main/java/sandbox/semo/domain/member/entity/Member.java
  semo-core/src/main/java/sandbox/semo/domain/member/entity/Role.java
  semo-core/src/main/java/sandbox/semo/domain/member/repository/MemberRepository.java
Labels: ✨ Feat, ♻️ Refactor, :hammer: Fix

#34 [Feat] 시계열 데이터 차트 모니터링을 위한 Batch 시스템 구축
  semo-batch/src/main/java/sandbox/semo/batch/dto/DeviceInfo.java
  semo-batch/src/main/java/sandbox/semo/batch/repository/JdbcRepository.java
  semo-batch/src/main/java/sandbox/semo/batch/repository/mapper/MetricDataRowMapper.java
  semo-batch/src/main/java/sandbox/semo/batch/repository/mapper/SessionDataRowMapper.java
  semo-batch/src/main/java/sandbox/semo/batch/service/step/DeviceProcessor.java
  semo-batch/src/main/java/sandbox/semo/batch/service/step/DeviceWriter.java
  semo-batch/src/main/resources/sql/batch-queries.properties
  semo-core/src/main/java/sandbox/semo/domain/collection/entity/MonitoringMetric.java
  semo-core/src/main/java/sandbox/semo/domain/collection/entity/MonitoringMetricId.java
Labels: ✨ Feat

#14 [Feat] 회원 이메일 발송 API
  build.gradle
  semo-api/src/main/java/sandbox/semo/application/email/controller/EmailController.java
  semo-api/src/main/java/sandbox/semo/application/email/exception/EmailBusinessException.java
  semo-api/src/main/java/sandbox/semo/application/email/exception/EmailErrorCode.java
  semo-api/src/main/java/sandbox/semo/application/email/service/EmailService.java
  semo-api/src/main/java/sandbox/semo/application/email/service/EmailServiceImpl.java
  semo-api/src/main/resources/application.yml
  semo-api/src/main/resources/img/Block.png
  semo-api/src/main/resources/templates/company-registration.html
  semo-api/src/main/resources/templates/company-rejection.html
  semo-api/src/main/resources/templates/member-registration.html
  semo-api/src/main/resources/templates/member-rejection.html
  semo-api/src/main/resources/templates/send-auth-code.html
  semo-core/src/main/java/sandbox/semo/domain/company/repository/CompanyFormRepository.java
  semo-core/src/main/java/sandbox/semo/domain/member/dto/request/EmailAuthVerify.java
  semo-core/src/main/java/sandbox/semo/domain/member/dto/request/EmailSendRequest.java
Labels: ✨ Feat
